### ISSUE TITLE
Population tier 3-5 is to high

### ISSUE THREAD

**Issue by auipga** [Beesbeesbeesbees/anno1800assistant#6]
Artisans, Engineers and Investors are always 5 to much.

**Comment by auipga** [comment]
Possibly fixed by https://github.com/Beesbeesbeesbees/anno1800assistant/pull/3

**Comment by shawnraisbeck** [comment]
The website needs to be updated to the version with this fix.

**Comment by Beesbeesbeesbees** [comment]
Thanks, sorry for the delay
